react-list-cmpc
Wolox/frontend-cookbook pull request #132
Opened 2021-03-18 15:46 UTC by ema999

## Summary

Adding a new collapsable list with remove option from CMPC project

## Screenshots
![list](https://user-images.githubusercontent.com/26144389/111654778-d3783e00-87e7-11eb-961f-7721a2b19c7e.gif)

2021-03-19 21:12 UTC, damfinkel requested changes

2021-03-19 21:12 UTC, damfinkel commented on cookbook-react/src/recipes/lists/list-cmpc/index.tsx
> +    const itemsfiltered: Item[] = itemsList.filter((item: Item) => item.id !== id);
`filteredItems`

In english, the noun modifier is always before the noun itself, for example: `black cat`, `big house`, `modified element`, `filtered items`

2021-03-19 21:12 UTC, damfinkel commented on cookbook-react/src/recipes/lists/list-cmpc/index.tsx
> +List.defaultProps = {
Add here as well the comment that this is only for example purposes and to remove it in a real project.

2021-03-19 21:12 UTC, damfinkel commented on cookbook-react/src/recipes/lists/list-cmpc/styles.module.scss
> +.close-icon {
In the image it seems like the close icon is not centered vertically, please check that

2021-03-19 21:12 UTC, damfinkel commented on cookbook-react/src/recipes/lists/list-cmpc/styles.module.scss
> +  font-weight: 700;
sort properties

2021-03-19 21:12 UTC, damfinkel commented on cookbook-react/src/recipes/lists/list-cmpc/styles.module.scss
> +  width: 20px;
sort properties

2021-03-19 21:12 UTC, damfinkel commented on cookbook-react/src/recipes/lists/list-cmpc/index.tsx
> +import React, { useState } from 'react';
Can we change the name of the folder to `cmpc list`?

2021-03-29 18:41 UTC, alejobh commented
tests please

2021-05-14 22:11 UTC, alejobh approved these changes

2021-05-17 19:14 UTC, pabloferro requested changes

2021-05-17 19:14 UTC, pabloferro commented on cookbook-react/src/hooks/useCollapse/index.tsx
> +    calculateHeight();
```suggestion
    collapsibleRef.current!.style.transition = `height ${collapseTime}ms ease-out, padding ${collapseTime}ms ease-out, margin ${collapseTime}ms ease-out`;
    collapsibleRef.current!.style.overflow = 'hidden';

    calculateHeight();
```
What if current is not defined yet 🤔 , why don't you add an if?

2021-05-17 19:14 UTC, pabloferro commented on cookbook-react/src/recipes/lists/valparaiso/Item/styles.module.scss
> +$black: #000;
I'd use constants with semantic meaning, like primary, disabled, background, etc.

2021-05-17 19:14 UTC, pabloferro commented on cookbook-react/src/recipes/lists/valparaiso/List/styles.module.scss
> +$black: #000;
Same here 😄

2021-05-17 19:14 UTC, pabloferro commented on cookbook-react/src/recipes/lists/valparaiso/List/styles.module.scss
> +  padding: 20px 20px 20px 25px;
_suggestion: I think it's clearer._
```suggestion
  padding: 20px;
  padding-left: 25px;
```

2021-05-17 20:28 UTC, pabloferro approved these changes

2021-05-17 20:43 UTC, merged